# Generated by Django 5.1.3 on 2025-03-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(default=0, max_length=128)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('lux', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='Base.sensor_id')),
            ],
        ),
    ]
